# Generated by Django 4.2.16 on 2025-09-27 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tahsilat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TahsilatEvrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahsilat_id', models.IntegerField(help_text='TAHSILATTB tablosundaki ID', verbose_name='Tahsilat ID')),
                ('cari_kod', models.CharField(blank=True, max_length=50, verbose_name='Cari Kod')),
                ('evrak_no', models.CharField(blank=True, max_length=100, verbose_name='Evrak No')),
                ('evrak_dosyasi', models.FileField(upload_to=tahsilat.models.evrak_upload_path, verbose_name='Evrak Dosyası')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('dosya_boyutu', models.IntegerField(blank=True, null=True, verbose_name='Dosya Boyutu (byte)')),
                ('yukleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Tahsilat Evrak',
                'verbose_name_plural': 'Tahsilat Evrakları',
                'ordering': ['-yukleme_tarihi'],
            },
        ),
    ]
