# Generated by Django 4.2.16 on 2025-10-21 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahsilat', '0002_gidermasraf_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tahsilatevrak',
            options={'ordering': ['-yuklenen_tarih'], 'verbose_name': 'Tahsilat Evrak', 'verbose_name_plural': 'Tahsilat Evrakları'},
        ),
        migrations.RemoveField(
            model_name='tahsilatevrak',
            name='yukleme_tarihi',
        ),
        migrations.AddField(
            model_name='tahsilatevrak',
            name='yuklenen_tarih',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yükleme Tarihi'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KullaniciYetki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_adi', models.CharField(choices=[('dashboard', 'Dashboard'), ('genel_gorunum', 'Genel Görünüm'), ('satislar', 'Satışlar'), ('tahsilatlar', 'Tahsilatlar'), ('alimlar', 'Alımlar'), ('muhasebe', 'Muhasebe'), ('gider_masraf', 'Gider Masraf'), ('perakende', 'Perakende'), ('klasik_tahsilat_raporu', 'Klasik Tahsilat Raporu'), ('yetkilendirme', 'Yetkilendirme')], max_length=50, verbose_name='Menü Adı')),
                ('erisim_izni', models.BooleanField(default=False, verbose_name='Erişim İzni')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturulan_yetkiler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Kullanıcı Yetki',
                'verbose_name_plural': 'Kullanıcı Yetkileri',
                'ordering': ['kullanici__username', 'menu_adi'],
                'unique_together': {('kullanici', 'menu_adi')},
            },
        ),
    ]
