# Generated by Django 4.2.16 on 2025-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0004_alter_kullaniciyetki_menu_adi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullaniciyetki',
            name='menu_adi',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('genel_gorunum', 'Genel Görünüm'), ('satislar', 'Satışlar'), ('tahsilatlar', 'Tahsilatlar'), ('alimlar', 'Alımlar'), ('muhasebe', 'Muhasebe'), ('gider_masraf', 'Gider Masraf'), ('perakende', 'Perakende'), ('klasik_tahsilat_raporu', 'Klasik Tahsilat Raporu'), ('yetkilendirme', 'Yetkilendirme'), ('cari_ekstre', 'Cari Ekstre'), ('yeni_tahsilat', 'Yeni Tahsilat'), ('stok_yonetimi', 'Stok Yönetimi'), ('cari_yonetimi', 'Cari Yönetimi'), ('cari_gecikmeleri', 'Cari Geçiklemeleri')], max_length=50, verbose_name='Menü Adı'),
        ),
    ]
