# Generated by Django 4.2.16 on 2025-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0005_alter_kullaniciyetki_menu_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CariGeckme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_kod', models.CharField(db_index=True, max_length=50, verbose_name='Cari Kod')),
                ('cari_unvan', models.CharField(max_length=200, verbose_name='Cari Ünvan')),
                ('gecikme_tutari', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Geçikme Tutarı')),
                ('gecikme_fatura_sayisi', models.IntegerField(verbose_name='Geçikme Fatura Sayısı')),
                ('en_eski_vade', models.DateField(verbose_name='En Eski Vade')),
                ('en_yeni_vade', models.DateField(verbose_name='En Yeni Vade')),
                ('gecikme_gun_sayisi', models.IntegerField(verbose_name='Geçikme Gün Sayısı')),
                ('hesaplama_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Hesaplama Tarihi')),
            ],
            options={
                'verbose_name': 'Cari Geçikme',
                'verbose_name_plural': 'Cari Geçikmeleri',
                'ordering': ['-gecikme_tutari'],
                'indexes': [models.Index(fields=['cari_kod'], name='tahsilat_ca_cari_ko_4d0fbf_idx'), models.Index(fields=['-gecikme_tutari'], name='tahsilat_ca_gecikme_597c9b_idx'), models.Index(fields=['hesaplama_tarihi'], name='tahsilat_ca_hesapla_9aad83_idx')],
            },
        ),
    ]
