# Generated by Django 4.2.16 on 2025-10-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahsilat', '0007_alter_kullaniciyetki_menu_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('okunma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_mesajlar', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
