# Generated by Django 4.2.16 on 2025-10-22 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahsilat', '0009_alter_kullaniciyetki_menu_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son_aktivite', models.DateTimeField(auto_now=True, verbose_name='Son Aktivite')),
                ('cevrimici', models.BooleanField(default=True, verbose_name='Çevrimiçi')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Durumu',
                'verbose_name_plural': 'Kullanıcı Durumları',
            },
        ),
    ]
