# Generated by Django 4.2.16 on 2025-10-22 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahsilat', '0010_kullanicidurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullaniciyetki',
            name='menu_adi',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('genel_gorunum', 'Genel Görünüm'), ('satislar', 'Satışlar'), ('tahsilatlar', 'Tahsilatlar'), ('alimlar', 'Alımlar'), ('muhasebe', 'Muhasebe'), ('gider_masraf', 'Gider Masraf'), ('perakende', 'Perakende'), ('klasik_tahsilat_raporu', 'Klasik Tahsilat Raporu'), ('yetkilendirme', 'Yetkilendirme'), ('cari_ekstre', 'Cari Ekstre'), ('yeni_tahsilat', 'Yeni Tahsilat'), ('stok_yonetimi', 'Stok Yönetimi'), ('cari_yonetimi', 'Cari Yönetimi'), ('cari_gecikmeleri', 'Cari Geçiklemeleri'), ('muhasebe_yeni_tahsilat', 'Muhasebe > Yeni Tahsilat'), ('muhasebe_tahsilat_listesi', 'Muhasebe > Tahsilat Listesi'), ('muhasebe_klasik_rapor', 'Muhasebe > Klasik Rapor'), ('genel_dashboard', 'Genel Görünüm > Dashboard'), ('genel_tahsilatlar', 'Genel Görünüm > Tahsilatlar'), ('genel_satislar', 'Genel Görünüm > Satışlar'), ('genel_alimlar', 'Genel Görünüm > Alımlar'), ('genel_ekstre', 'Genel Görünüm > Ekstre'), ('stok_listesi', 'Stok Yönetimi > Stok Listesi'), ('fiyat_analizi', 'Stok Yönetimi > Fiyat Analizi'), ('stok_detayli_analiz', 'Stok Yönetimi > Detaylı Analiz'), ('cari_analiz', 'Cari Yönetimi > Cari Analiz'), ('cari_vade_analizi', 'Cari Yönetimi > Vade Analizi'), ('cari_gecikmeleri_detay', 'Cari Yönetimi > Geçikmeleri'), ('chat', 'Mesajlaşma'), ('logo_transfer', 'LOGOYA AKTAR')], max_length=50, verbose_name='Menü Adı'),
        ),
        migrations.CreateModel(
            name='LogoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheno', models.CharField(max_length=17, verbose_name='Fiş Numarası')),
                ('trcode', models.SmallIntegerField(verbose_name='İşlem Kodu')),
                ('credit', models.FloatField(verbose_name='Kredi Tutarı')),
                ('repcredit', models.FloatField(verbose_name='Rapor Kredi Tutarı')),
                ('tarih', models.DateTimeField(verbose_name='Tarih')),
                ('clientref', models.IntegerField(default=421, verbose_name='Müşteri Referansı')),
                ('sourcefref', models.IntegerField(blank=True, null=True, verbose_name='Kaynak Fiş Referansı')),
                ('tranno', models.CharField(blank=True, max_length=17, verbose_name='İşlem Numarası')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Tutar')),
                ('trnet', models.FloatField(blank=True, null=True, verbose_name='İşlem Net Tutarı')),
                ('reportnet', models.FloatField(blank=True, null=True, verbose_name='Rapor Net Tutarı')),
                ('bnlnnet', models.FloatField(blank=True, null=True, verbose_name='Banka Net Tutarı')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('isleniyor', 'İşleniyor'), ('basarili', 'Başarılı'), ('hata', 'Hata')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('hata_mesaji', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'LOGO Aktarım',
                'verbose_name_plural': 'LOGO Aktarımları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
