# Generated by Django 4.2.16 on 2025-10-24 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahsilat', '0011_alter_kullaniciyetki_menu_adi_logotransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='Menü Adı')),
                ('has_access', models.BooleanField(default=False, verbose_name='Erişim İzni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Yetkisi',
                'verbose_name_plural': 'Kullanıcı Yetkileri',
                'unique_together': {('user', 'menu_name')},
            },
        ),
    ]
