# Generated by Django 4.2.16 on 2025-10-24 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahsilat', '0012_userpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CekSenet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_turu', models.CharField(choices=[('cek', 'Çek'), ('senet', 'Senet'), ('kredi', 'Kredi'), ('kredi_karti', 'Kredi Kartı')], max_length=20, verbose_name='Ödeme Türü')),
                ('tip', models.CharField(choices=[('gelen', 'Gelen'), ('giden', 'Giden')], max_length=10, verbose_name='Tip')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('odendi', 'Ödendi'), ('iptal', 'İptal'), ('vadesi_gecti', 'Vadesi Geçti')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('para_birimi', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('islem_tarihi', models.DateField(verbose_name='İşlem Tarihi')),
                ('vade_tarihi', models.DateField(verbose_name='Vade Tarihi')),
                ('odeme_tarihi', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('cari_kod', models.CharField(max_length=50, verbose_name='Cari Kod')),
                ('cari_unvan', models.CharField(max_length=200, verbose_name='Cari Ünvan')),
                ('banka_adi', models.CharField(blank=True, max_length=100, verbose_name='Banka Adı')),
                ('cek_senet_no', models.CharField(blank=True, max_length=50, verbose_name='Çek/Senet No')),
                ('banka_sube', models.CharField(blank=True, max_length=100, verbose_name='Banka Şubesi')),
                ('hesap_no', models.CharField(blank=True, max_length=50, verbose_name='Hesap No')),
                ('kredi_turu', models.CharField(blank=True, max_length=50, verbose_name='Kredi Türü')),
                ('faiz_orani', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Faiz Oranı (%)')),
                ('taksit_sayisi', models.IntegerField(blank=True, null=True, verbose_name='Taksit Sayısı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Çek ve Senet',
                'verbose_name_plural': 'Çek ve Senetler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
