# Generated by Django 4.2.16 on 2025-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0014_alter_ceksenet_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceksenet',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('ciro', 'Ciro'), ('odendi', 'Ödendi'), ('iptal', 'İptal'), ('vadesi_gecti', 'Vadesi Geçti')], default='beklemede', max_length=20, verbose_name='Durum'),
        ),
    ]
