# Generated by Django 4.2.16 on 2025-11-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0015_alter_ceksenet_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='carigeckme',
            name='bolge',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bölge'),
        ),
        migrations.AddField(
            model_name='carigeckme',
            name='plasiyer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Plasiyer'),
        ),
        migrations.AlterField(
            model_name='kullaniciyetki',
            name='menu_adi',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('genel_gorunum', 'Genel Görünüm'), ('satislar', 'Satışlar'), ('tahsilatlar', 'Tahsilatlar'), ('alimlar', 'Alımlar'), ('muhasebe', 'Muhasebe'), ('gider_masraf', 'Gider Masraf'), ('perakende', 'Perakende'), ('klasik_tahsilat_raporu', 'Klasik Tahsilat Raporu'), ('kdv_raporu', 'KDV Raporu'), ('yetkilendirme', 'Yetkilendirme'), ('cari_ekstre', 'Cari Ekstre'), ('yeni_tahsilat', 'Yeni Tahsilat'), ('stok_yonetimi', 'Stok Yönetimi'), ('cari_yonetimi', 'Cari Yönetimi'), ('cari_gecikmeleri', 'Cari Geçiklemeleri'), ('muhasebe_yeni_tahsilat', 'Muhasebe > Yeni Tahsilat'), ('muhasebe_tahsilat_listesi', 'Muhasebe > Tahsilat Listesi'), ('muhasebe_klasik_rapor', 'Muhasebe > Klasik Rapor'), ('muhasebe_gunluk_rapor', 'Muhasebe > Günlük Rapor'), ('genel_dashboard', 'Genel Görünüm > Dashboard'), ('genel_tahsilatlar', 'Genel Görünüm > Tahsilatlar'), ('genel_satislar', 'Genel Görünüm > Satışlar'), ('genel_alimlar', 'Genel Görünüm > Alımlar'), ('genel_ekstre', 'Genel Görünüm > Ekstre'), ('stok_listesi', 'Stok Yönetimi > Stok Listesi'), ('fiyat_analizi', 'Stok Yönetimi > Fiyat Analizi'), ('stok_detayli_analiz', 'Stok Yönetimi > Detaylı Analiz'), ('cari_analiz', 'Cari Yönetimi > Cari Analiz'), ('cari_vade_analizi', 'Cari Yönetimi > Vade Analizi'), ('cari_gecikmeleri_detay', 'Cari Yönetimi > Geçikmeleri'), ('chat', 'Mesajlaşma'), ('logo_transfer', 'LOGOYA AKTAR'), ('cek_senetler', 'Çek ve Senetler')], max_length=50, verbose_name='Menü Adı'),
        ),
    ]
