# Generated by Django 4.2.16 on 2026-01-16 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahsilat', '0016_carigeckme_bolge_carigeckme_plasiyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullaniciyetki',
            name='menu_adi',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('genel_gorunum', 'Genel Görünüm'), ('satislar', 'Satışlar'), ('tahsilatlar', 'Tahsilatlar'), ('alimlar', 'Alımlar'), ('muhasebe', 'Muhasebe'), ('gider_masraf', 'Gider Masraf'), ('perakende', 'Perakende'), ('klasik_tahsilat_raporu', 'Klasik Tahsilat Raporu'), ('kdv_raporu', 'KDV Raporu'), ('yetkilendirme', 'Yetkilendirme'), ('cari_ekstre', 'Cari Ekstre'), ('yeni_tahsilat', 'Yeni Tahsilat'), ('stok_yonetimi', 'Stok Yönetimi'), ('cari_yonetimi', 'Cari Yönetimi'), ('cari_gecikmeleri', 'Cari Geçiklemeleri'), ('muhasebe_yeni_tahsilat', 'Muhasebe > Yeni Tahsilat'), ('muhasebe_tahsilat_listesi', 'Muhasebe > Tahsilat Listesi'), ('muhasebe_klasik_rapor', 'Muhasebe > Klasik Rapor'), ('muhasebe_gunluk_rapor', 'Muhasebe > Günlük Rapor'), ('genel_dashboard', 'Genel Görünüm > Dashboard'), ('genel_tahsilatlar', 'Genel Görünüm > Tahsilatlar'), ('genel_satislar', 'Genel Görünüm > Satışlar'), ('genel_alimlar', 'Genel Görünüm > Alımlar'), ('genel_ekstre', 'Genel Görünüm > Ekstre'), ('genel_cari_analiz', 'Genel Görünüm > Cari Genel Analiz'), ('stok_listesi', 'Stok Yönetimi > Stok Listesi'), ('fiyat_analizi', 'Stok Yönetimi > Fiyat Analizi'), ('stok_detayli_analiz', 'Stok Yönetimi > Detaylı Analiz'), ('cari_bakiyeler', 'Cari Yönetimi > Cari Bakiyeler'), ('cari_analiz', 'Cari Yönetimi > Cari Analiz'), ('cari_vade_analizi', 'Cari Yönetimi > Vade Analizi'), ('cari_gecikmeleri_detay', 'Cari Yönetimi > Geçikmeleri'), ('chat', 'Mesajlaşma'), ('logo_transfer', 'LOGOYA AKTAR'), ('cek_senetler', 'Çek ve Senetler'), ('tahsilatlarim', 'Tahsilatlarım'), ('satislarim', 'Satışlarım')], max_length=50, verbose_name='Menü Adı'),
        ),
        migrations.CreateModel(
            name='PlasiyerPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasiyer', models.CharField(choices=[('ALİ', 'ALİ'), ('AZİZ', 'AZİZ'), ('EYÜP', 'EYÜP'), ('NECATİ', 'NECATİ'), ('HASAN', 'HASAN'), ('YİĞİT', 'YİĞİT'), ('ATAKAN', 'ATAKAN')], max_length=50, verbose_name='Plasiyer')),
                ('donem_ay', models.IntegerField(verbose_name='Dönem Ay')),
                ('donem_yil', models.IntegerField(verbose_name='Dönem Yıl')),
                ('nakit_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Nakit Toplam')),
                ('kredi_karti_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kredi Kartı Toplam')),
                ('havale_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Havale Toplam')),
                ('cek_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Çek Toplam')),
                ('senet_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Senet Toplam')),
                ('gecikme_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gecikme Tutarı')),
                ('toplam_prim', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Prim')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Plasiyer Prim',
                'verbose_name_plural': 'Plasiyer Primleri',
                'ordering': ['-donem_yil', '-donem_ay', 'plasiyer'],
                'unique_together': {('plasiyer', 'donem_ay', 'donem_yil')},
            },
        ),
    ]
