# Generated by Django 4.2.16 on 2026-04-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0019_add_ortalama_maliyet_menu_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ayar Anahtarı')),
                ('value', models.BooleanField(default=True, verbose_name='Ayar Kapalı/Açık Değeri')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
            },
        ),
        migrations.AlterField(
            model_name='plasiyerprim',
            name='plasiyer',
            field=models.CharField(choices=[('ALİ', 'ALİ'), ('AZİZ', 'AZİZ'), ('CAN', 'CAN'), ('EYÜP', 'EYÜP'), ('NECATİ', 'NECATİ'), ('HASAN', 'HASAN'), ('YİĞİT', 'YİĞİT'), ('ATAKAN', 'ATAKAN')], max_length=50, verbose_name='Plasiyer'),
        ),
    ]
