# Generated by Django 4.2.16 on 2026-05-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0020_systemsettings_alter_plasiyerprim_plasiyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HakedisHedef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasiyer', models.CharField(choices=[('ALİ', 'ALİ'), ('AZİZ', 'AZİZ'), ('CAN', 'CAN'), ('EYÜP', 'EYÜP'), ('NECATİ', 'NECATİ'), ('HASAN', 'HASAN'), ('YİĞİT', 'YİĞİT'), ('ATAKAN', 'ATAKAN')], max_length=50, verbose_name='Plasiyer')),
                ('donem_ay', models.PositiveSmallIntegerField(verbose_name='Dönem Ay')),
                ('donem_yil', models.PositiveSmallIntegerField(verbose_name='Dönem Yıl')),
                ('kademe_no', models.PositiveSmallIntegerField(default=1, verbose_name='Kademe No')),
                ('marka', models.CharField(max_length=100, verbose_name='Marka')),
                ('malzeme_turu', models.CharField(blank=True, default='', max_length=100, verbose_name='Malzeme Türü')),
                ('hedef_tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Hedef Tutar')),
                ('hakedis_yuzde', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hakediş Yüzdesi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_hakedis_hedefleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Hakediş Hedefi',
                'verbose_name_plural': 'Hakediş Hedefleri',
                'ordering': ['-donem_yil', '-donem_ay', 'marka', 'malzeme_turu', 'kademe_no', 'plasiyer'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hakedishedef',
            unique_together={('plasiyer', 'donem_ay', 'donem_yil', 'kademe_no', 'marka', 'malzeme_turu')},
        ),
        migrations.AddIndex(
            model_name='hakedishedef',
            index=models.Index(fields=['donem_yil', 'donem_ay'], name='tahsilat_h_donem_y_273547_idx'),
        ),
        migrations.AddIndex(
            model_name='hakedishedef',
            index=models.Index(fields=['marka', 'malzeme_turu'], name='tahsilat_h_marka_5e4a17_idx'),
        ),
        migrations.AddIndex(
            model_name='hakedishedef',
            index=models.Index(fields=['plasiyer', 'aktif'], name='tahsilat_h_plasiy_0a32b9_idx'),
        ),
        migrations.AlterField(
            model_name='kullaniciyetki',
            name='menu_adi',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('genel_gorunum', 'Genel Görünüm'), ('hakedis_yonetimi', 'Hakediş Yönetimi'), ('satislar', 'Satışlar'), ('tahsilatlar', 'Tahsilatlar'), ('alimlar', 'Alımlar'), ('muhasebe', 'Muhasebe'), ('gider_masraf', 'Gider Masraf'), ('perakende', 'Perakende'), ('klasik_tahsilat_raporu', 'Klasik Tahsilat Raporu'), ('kdv_raporu', 'KDV Raporu'), ('yetkilendirme', 'Yetkilendirme'), ('cari_ekstre', 'Cari Ekstre'), ('yeni_tahsilat', 'Yeni Tahsilat'), ('stok_yonetimi', 'Stok Yönetimi'), ('cari_yonetimi', 'Cari Yönetimi'), ('cari_gecikmeleri', 'Cari Geçiklemeleri'), ('muhasebe_yeni_tahsilat', 'Muhasebe > Yeni Tahsilat'), ('muhasebe_tahsilat_listesi', 'Muhasebe > Tahsilat Listesi'), ('muhasebe_klasik_rapor', 'Muhasebe > Klasik Rapor'), ('muhasebe_gunluk_rapor', 'Muhasebe > Günlük Rapor'), ('genel_dashboard', 'Genel Görünüm > Dashboard'), ('genel_tahsilatlar', 'Genel Görünüm > Tahsilatlar'), ('genel_satislar', 'Genel Görünüm > Satışlar'), ('genel_alimlar', 'Genel Görünüm > Alımlar'), ('genel_ekstre', 'Genel Görünüm > Ekstre'), ('genel_cari_analiz', 'Genel Görünüm > Cari Genel Analiz'), ('genel_cari_aylik_ozet', 'Genel Görünüm > Cari Aylık Özet'), ('plasiyer_hedef_durumu', 'Hakediş Yönetimi > Plasiyer Hedef Durumu'), ('hedef_belirleme', 'Hakediş Yönetimi > Hedef Belirleme'), ('stok_listesi', 'Stok Yönetimi > Stok Listesi'), ('fiyat_analizi', 'Stok Yönetimi > Fiyat Analizi'), ('stok_detayli_analiz', 'Stok Yönetimi > Detaylı Analiz'), ('ortalama_maliyet', 'Stok Yönetimi > Ortalama Maliyet'), ('cari_bakiyeler', 'Cari Yönetimi > Cari Bakiyeler'), ('cari_analiz', 'Cari Yönetimi > Cari Analiz'), ('cari_vade_analizi', 'Cari Yönetimi > Vade Analizi'), ('cari_gecikmeleri_detay', 'Cari Yönetimi > Geçikmeleri'), ('chat', 'Mesajlaşma'), ('logo_transfer', 'LOGOYA AKTAR'), ('cek_senetler', 'Çek ve Senetler'), ('tahsilatlarim', 'Tahsilatlarım'), ('satislarim', 'Satışlarım')], max_length=50, verbose_name='Menü Adı'),
        ),
    ]
