# Generated by Django 4.2.16 on 2026-06-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0027_add_yapay_zeka_menu_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakedishedef',
            name='plasiyer',
            field=models.CharField(choices=[('ALİ', 'ALİ'), ('AZİZ', 'AZİZ'), ('CAN', 'CAN'), ('EYÜP', 'EYÜP'), ('BAKIR', 'BAKIR'), ('YİĞİT', 'YİĞİT'), ('ATAKAN', 'ATAKAN'), ('HALİL', 'HALİL')], max_length=50, verbose_name='Plasiyer'),
        ),
        migrations.AlterField(
            model_name='plasiyerprim',
            name='plasiyer',
            field=models.CharField(choices=[('ALİ', 'ALİ'), ('AZİZ', 'AZİZ'), ('CAN', 'CAN'), ('EYÜP', 'EYÜP'), ('BAKIR', 'BAKIR'), ('YİĞİT', 'YİĞİT'), ('ATAKAN', 'ATAKAN'), ('HALİL', 'HALİL')], max_length=50, verbose_name='Plasiyer'),
        ),
    ]
