# Generated by Cursor - Karlılık menü seçeneği eklendi

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahsilat', '0029_add_plasiyer_prim_menu_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullaniciyetki',
            name='menu_adi',
            field=models.CharField(
                choices=[
                    ('dashboard', 'Dashboard'),
                    ('genel_gorunum', 'Genel Görünüm'),
                    ('hakedis_yonetimi', 'Hakediş Yönetimi'),
                    ('satislar', 'Satışlar'),
                    ('tahsilatlar', 'Tahsilatlar'),
                    ('alimlar', 'Alımlar'),
                    ('muhasebe', 'Muhasebe'),
                    ('gider_masraf', 'Gider Masraf'),
                    ('perakende', 'Perakende'),
                    ('klasik_tahsilat_raporu', 'Klasik Tahsilat Raporu'),
                    ('kdv_raporu', 'KDV Raporu'),
                    ('yetkilendirme', 'Yetkilendirme'),
                    ('cari_ekstre', 'Cari Ekstre'),
                    ('yeni_tahsilat', 'Yeni Tahsilat'),
                    ('stok_yonetimi', 'Stok Yönetimi'),
                    ('cari_yonetimi', 'Cari Yönetimi'),
                    ('cari_gecikmeleri', 'Cari Geçiklemeleri'),
                    ('muhasebe_yeni_tahsilat', 'Muhasebe > Yeni Tahsilat'),
                    ('muhasebe_tahsilat_listesi', 'Muhasebe > Tahsilat Listesi'),
                    ('muhasebe_klasik_rapor', 'Muhasebe > Klasik Rapor'),
                    ('muhasebe_gunluk_rapor', 'Muhasebe > Günlük Rapor'),
                    ('genel_dashboard', 'Genel Görünüm > Dashboard'),
                    ('genel_tahsilatlar', 'Genel Görünüm > Tahsilatlar'),
                    ('genel_satislar', 'Genel Görünüm > Satışlar'),
                    ('genel_alimlar', 'Genel Görünüm > Alımlar'),
                    ('genel_ekstre', 'Genel Görünüm > Ekstre'),
                    ('genel_cari_analiz', 'Genel Görünüm > Cari Genel Analiz'),
                    ('genel_cari_aylik_ozet', 'Genel Görünüm > Cari Aylık Özet'),
                    ('plasiyer_prim', 'Genel Görünüm > Plasiyer Prim'),
                    ('genel_karlilik', 'Genel Görünüm > Karlılık'),
                    ('plasiyer_hedef_durumu', 'Hakediş Yönetimi > Plasiyer Hedef Durumu'),
                    ('hedeflerim', 'Hakediş Yönetimi > Hedeflerim'),
                    ('hedef_belirleme', 'Hakediş Yönetimi > Hedef Belirleme'),
                    ('stok_listesi', 'Stok Yönetimi > Stok Listesi'),
                    ('fiyat_analizi', 'Stok Yönetimi > Fiyat Analizi'),
                    ('stok_detayli_analiz', 'Stok Yönetimi > Detaylı Analiz'),
                    ('ortalama_maliyet', 'Stok Yönetimi > Ortalama Maliyet'),
                    ('cari_bakiyeler', 'Cari Yönetimi > Cari Bakiyeler'),
                    ('cari_analiz', 'Cari Yönetimi > Cari Analiz'),
                    ('cari_vade_analizi', 'Cari Yönetimi > Vade Analizi'),
                    ('cari_gecikmeleri_detay', 'Cari Yönetimi > Geçikmeleri'),
                    ('chat', 'Mesajlaşma'),
                    ('yapay_zeka', 'Yapay Zeka'),
                    ('logo_transfer', 'LOGOYA AKTAR'),
                    ('cek_senetler', 'Çek ve Senetler'),
                    ('tahsilatlarim', 'Tahsilatlarım'),
                    ('satislarim', 'Satışlarım'),
                ],
                max_length=50,
                verbose_name='Menü Adı',
            ),
        ),
    ]